version: '2'
services:
    logistics-app:
        image: logistics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://logistics-postgresql:5432/logistics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8998:8998
    logistics-postgresql:
        extends:
            file: postgresql.yml
            service: logistics-postgresql
