version: '2'
services:
    logistics-cassandra:
        container_name: logistics-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/logistics/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    logistics-cassandra-node:
        image: cassandra:3.9
        links:
            - logistics-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    logistics-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: logistics-cassandra-migration
        links:
            - logistics-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
